# Generated by Django 4.2 on 2023-04-23 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_customer_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="books",
            name="book_id",
        ),
    ]
