# Generated by Django 4.2 on 2023-04-25 16:39

from django.db import migrations
from django.db.migrations import RunPython

def func(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', 'fixture_data.json')


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        RunPython(func, reverse_func)
    ]
